export const Routes = {
  ORGANIZATION_TRACE: '/organization-trace',
  ADMINISTRATION: {
    TEXT_TEMPLATES: '/text-templates',
    AUDIT_LOGS: '/audit-logs',
    SETTINGS: '/setting-management',
    ORGANIZATION_UNITS: '/organization-units',
    ROLES: '/roles',
    USERS: '/users',
    SECURITY_LOGS: '/security-logs',
    LANGUAGES: '/language-management/languages',
    LANGUAGES_TEXTS: '/language-management/texts',
  },
  INVENTORY_MANAGEMENT: {
    WAREHOUSES: '/warehouses',
    EDIT_WAREHOUSE: '/warehouses/edit-warehouse/:warehouseId',
    WAREHOUSE_INVENTORIES: '/warehouses/:warehouseId/inventories',
    WAREHOUSE_STOCK_CHANGES: '/warehouses/:warehouseId/stock-changes',
    WAREHOUSE_INVENTORIES_STOCK_CHANGES:
      '/warehouses/:warehouseId/inventories/:inventoryId/stock-changes',
    INVENTORIES_PRODUCT_STOCK_CHANGES:
      '/inventories/:inventoryId/stock-changes',
    PRODUCT_UNITS: '/product-units',
    PRODUCT_TYPES: '/product-types',
    PRODUCT_MANUFACTURERS: '/product-manufacturers',
    PRODUCT_BRANDS: '/product-brands',
    PRODUCT_BRAND_MODELS: '/product-brand-models',
    PRODUCTS: '/products',
  },
  DEFINITIONS: {
    ORGANIZATIONS: '/organizations',
    DEVICES: '/devices',
    DEVICE_MODELS: '/device-models',
    ACCESS_POINTS_TABLE: '/access-points',
    ALARM_CONFIGURATION_TABLE: '/alarm-configurations',
    LABEL_TABLE: '/labels',
    MULTI_CONDITIONAL_STATUSES: '/multi-conditional-statuses',
    MODBUS_TABLE: '/device-model-modbus-tables',
    MODBUS_TABLE_INFO: '/device-model-modbus-tables/:modbusTableId',
    DEVICE_CATEGORIES_TABLE: '/device-categories',
    FIRM_WEATHER_DATA_LOCATIONS: '/firm-weather-data-location-oWMS',
    TIME_PERIODS: '/time-periods',
    FORMULAS: '/formulas',
    MIMIC_DIAGRAM_EDITOR: '/mimic-diagram-editor',
    MIMIC_ELEMENTS: '/mimic-elements',
    HOURLY_ELEC_CUNSUMPTION_PRODUCTION_VALUES:
      '/device-elec-hourly-consumptions',
    ORGANIZATION_PLANT_DETAILS: '/organization-plant-details',
    DERIVED_VALUES: '/derived-values',
    SYSTEM_WEATHER_DATA_LOCATIONS: '/system-weather-data-location-oWMS',
    MIMIC_PROFILE: '/mimic-profile',
    PLANT_IMAGES: '/plant-images',
    PLANT_VIDEOS: '/plant-videos',
  },
  REPORTS: {
    PERIODIC_ELEC_PRODUCTION_CONSUMPTION_REPORTS:
      '/reports/periodic-production-consumptions',
    INDEX_VALUE_REPORTS: '/reports/index-values',
    INVERTER_INSTANT_VALUES_REPORTS: '/reports/inverter-instant-values',
    SENSOR_VALUE_REPORTS: '/reports/sensor-values',
    INSTANT_VALUE_REPORTS: '/reports/instant-values',
    ELEC_PRODUCTION_CONSUMPTION_REPORTS: '/reports/production-consumptions',
    WEATHER_REPORTS: '/reports/weather',
    SYSTEM_ALARM_REPORTS: '/reports/system-alarms',
    TAG_REPORTS: '/reports/tag-reports',
  },
  MAINTENANCE_AND_REPAIRS: {
    ASSET_TREE: '/asset-tree',
    ASSET_NODES: '/asset-nodes',
    PLANTS: '/plants',
    EDIT_PLANT: '/plants/edit-plant/:plantId',
    PLANTS_STOCK_CHANGES: '/plants/:plantId/stock-changes',
    PLANTS_INVENTORIES: '/plants/:plantId/inventories',
    WORK_NOTIFICATION_TYPES: '/work-notification-types',
    WORK_NOTIFICATIONS: '/work-notifications',
    WORK_ORDER_COST_TYPES: '/work-order-cost-types',
    WORK_ORDER_COSTS: '/work-order-cost',
    WORK_ORDERS: '/work-orders',
    WORK_ORDERS_WORKERS: '/work-orders-workers',
    WORK_ORDER_ACTIONS: '/work-order-actions',
    WORK_ORDER_TYPES: '/work-order-types',
    PLANT_DEVICE_TYPES: '/plant-device-types',
  },
};
