import { getTranslatedValue } from '@/helpers/get-translated-value';
import { CheckboxGroup } from '@/types/pages/reports/reports';

export const archiveReportFields: CheckboxGroup[] = [
  {
    id: 'Gerilim(Faz Nötr)',
    label: getTranslatedValue('Voltage.PhaseNeutral'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'VoltPNPhase1Avg' },
      { title: '1.Faz Min', fieldName: 'VoltPNPhase1Min' },
      { title: '1.Faz Maks.', fieldName: 'VoltPNPhase1Max' },
      { title: '2.Faz Ort.', fieldName: 'VoltPNPhase2Avg' },
      { title: '2.Faz Min.', fieldName: 'VoltPNPhase2Min' },
      { title: '2.Faz Maks.', fieldName: 'VoltPNPhase2Max' },
      { title: '3.Faz Ort.', fieldName: 'VoltPNPhase3Avg' },
      { title: '3.Faz Min.', fieldName: 'VoltPNPhase3Min' },
      { title: '3.Faz Maks.', fieldName: 'VoltPNPhase3Max' },
    ],
  },
  {
    id: 'Akım',
    label: getTranslatedValue('current'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'CurrentPhase1Avg' },
      { title: '1.Faz Min', fieldName: 'CurrentPhase1Min' },
      { title: '1.Faz Maks.', fieldName: 'CurrentPhase1Max' },
      { title: '2.Faz Ort.', fieldName: 'CurrentPhase2Avg' },
      { title: '2.Faz Min.', fieldName: 'CurrentPhase2Min' },
      { title: '2.Faz Maks.', fieldName: 'CurrentPhase2Max' },
      { title: '3.Faz Ort.', fieldName: 'CurrentPhase3Avg' },
      { title: '3.Faz Min.', fieldName: 'CurrentPhase3Min' },
      { title: '3.Faz Maks.', fieldName: 'CurrentPhase3Max' },
    ],
  },
  {
    id: 'Aktif Güç',
    label: getTranslatedValue('em_demand_active_power'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'ActivePowerPhase1Avg' },
      { title: '1.Faz Min', fieldName: 'ActivePowerPhase1Min' },
      { title: '1.Faz Maks.', fieldName: 'ActivePowerPhase1Max' },
      { title: '2.Faz Ort.', fieldName: 'ActivePowerPhase2Avg' },
      { title: '2.Faz Min.', fieldName: 'ActivePowerPhase2Min' },
      { title: '2.Faz Maks.', fieldName: 'ActivePowerPhase2Max' },
      { title: '3.Faz Ort.', fieldName: 'ActivePowerPhase3Avg' },
      { title: '3.Faz Min.', fieldName: 'ActivePowerPhase3Min' },
      { title: '3.Faz Maks.', fieldName: 'ActivePowerPhase3Max' },
    ],
  },
  {
    id: 'Reaktif Güç',
    label: getTranslatedValue('em_demand_reactive_power'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'ReactivePowerPhase1Avg' },
      { title: '1.Faz Min', fieldName: 'ReactivePowerPhase1Min' },
      { title: '1.Faz Maks.', fieldName: 'ReactivePowerPhase1Max' },
      { title: '2.Faz Ort.', fieldName: 'ReactivePowerPhase2Avg' },
      { title: '2.Faz Min.', fieldName: 'ReactivePowerPhase2Min' },
      { title: '2.Faz Maks.', fieldName: 'ReactivePowerPhase2Max' },
      { title: '3.Faz Ort.', fieldName: 'ReactivePowerPhase3Avg' },
      { title: '3.Faz Min.', fieldName: 'ReactivePowerPhase3Min' },
      { title: '3.Faz Maks.', fieldName: 'ReactivePowerPhase3Max' },
    ],
  },
  {
    id: 'Görünür Güç',
    label: getTranslatedValue('em_demand_apperant_power'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'ApparentPowerPhase1Avg' },
      { title: '1.Faz Min', fieldName: 'ApparentPowerPhase1Min' },
      { title: '1.Faz Maks.', fieldName: 'ApparentPowerPhase1Max' },
      { title: '2.Faz Ort.', fieldName: 'ApparentPowerPhase2Avg' },
      { title: '2.Faz Min.', fieldName: 'ApparentPowerPhase2Min' },
      { title: '2.Faz Maks.', fieldName: 'ApparentPowerPhase2Max' },
      { title: '3.Faz Ort.', fieldName: 'ApparentPowerPhase3Avg' },
      { title: '3.Faz Min.', fieldName: 'ApparentPowerPhase3Min' },
      { title: '3.Faz Maks.', fieldName: 'ApparentPowerPhase3Max' },
    ],
  },
  {
    id: 'Gerilim(Faz-Faz)',
    label: getTranslatedValue('Voltage.PhasePhase'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'VoltLL12Avg' },
      { title: '1.Faz Min', fieldName: 'VoltLL12Min' },
      { title: '1.Faz Maks.', fieldName: 'VoltLL12Max' },
      { title: '2.Faz Ort.', fieldName: 'VoltLL23Avg' },
      { title: '2.Faz Min.', fieldName: 'VoltLL23Min' },
      { title: '2.Faz Maks.', fieldName: 'VoltLL23Max' },
      { title: '3.Faz Ort.', fieldName: 'VoltLL31Avg' },
      { title: '3.Faz Min.', fieldName: 'VoltLL31Min' },
      { title: '3.Faz Maks.', fieldName: 'VoltLL31Max' },
    ],
  },
  {
    id: 'Cosø',
    label: getTranslatedValue('em_instant_cos'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'CosPhiPhase1Avg' },
      { title: '2.Faz Ort.', fieldName: 'CosPhiPhase2Avg' },
      { title: '3.Faz Ort.', fieldName: 'CosPhiPhase3Avg' },
    ],
  },
  {
    id: 'Güç Faktörü',
    label: getTranslatedValue('em_instant_power_factor'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'PowerFactorPhase1Avg' },
      { title: '2.Faz Ort.', fieldName: 'PowerFactorPhase2Avg' },
      { title: '3.Faz Ort.', fieldName: 'PowerFactorPhase3Avg' },
    ],
  },
  {
    id: 'Frekans',
    label: getTranslatedValue('em_instant_frequency'),
    values: [
      { title: '1.Faz Ort.', fieldName: 'FreqPhase1Avg' },
      { title: '1.Faz Min', fieldName: 'FreqPhase1Min' },
      { title: '1.Faz Maks.', fieldName: 'FreqPhase1Max' },
    ],
  },
  {
    id: 'Tüketim',
    label: getTranslatedValue('em_consumption'),
    values: [
      { title: 'Aktif Tük.', fieldName: 'EnergyActiveImport' },
      { title: 'Aktif Üre.', fieldName: 'EnergyActiveExport' },
      { title: 'Top. İndük.', fieldName: 'EnergyReactiveInductiveTotal' },
      { title: 'Top. Kap.', fieldName: 'EnergyReactiveCapacitiveTotal' },
      { title: 'İndük. Tük.', fieldName: 'EnergyReactiveInductiveImport' },
      { title: 'Kap. Tük.', fieldName: 'EnergyReactiveCapacitiveImport' },
      { title: 'İndük. Üre.', fieldName: 'EnergyReactiveInductiveExport' },
      { title: 'Kap. Üre.', fieldName: 'EnergyReactiveCapacitiveExport' },
    ],
  },
  {
    id: 'Demand',
    label: getTranslatedValue('Demand'),
    values: [
      { title: 'Aktif Güç Tük.', fieldName: 'ActivePowerDemandImport' },
      { title: 'Aktif Güç Üre.', fieldName: 'ActivePowerDemandExport' },
    ],
  },
];

export const SAMPLE_TABLE_DATA = [
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
];
