import { getTranslatedValue } from '@/helpers/get-translated-value';
import { CheckboxGroup } from '@/types/pages/reports/reports';

export const deviceStatusReportFields: CheckboxGroup[] = [
  {
    id: 'em_status_main',
    label: getTranslatedValue('em_status_main'),
    values: [
      {
        title: getTranslatedValue('InsDeviceDateTime'),
        fieldName: 'InsDeviceDateTime',
      },
      {
        title: getTranslatedValue('StatusBatteryVoltage'),
        fieldName: 'StatusBatteryVoltage',
      },
      {
        title: getTranslatedValue('StatusTemperature'),
        fieldName: 'StatusTemperature',
      },
      {
        title: getTranslatedValue('genarator_flag'),
        fieldName: 'StatusGenaratorFlag',
      },
    ],
  },
  {
    id: 'em_status_flag',
    label: getTranslatedValue('em_status_flag'),
    values: [
      {
        title: getTranslatedValue('AlarmFlag1'),
        fieldName: 'StatusAlarmFlag1',
      },
      {
        title: getTranslatedValue('AlarmFlag2'),
        fieldName: 'StatusAlarmFlag2',
      },
      {
        title: getTranslatedValue('StatusDigitalInputFlag'),
        fieldName: 'StatusDigitalInputFlag',
      },
      {
        title: getTranslatedValue('StatusDigitalOutputFlag'),
        fieldName: 'StatusDigitalOutputFlag',
      },
    ],
  },
  {
    id: 'em_working_info',
    label: getTranslatedValue('em_working_info'),
    values: [
      {
        title: getTranslatedValue('StatusRunHour'),
        fieldName: 'StatusRunHour',
      },
      {
        title: getTranslatedValue('StatusOnHour'),
        fieldName: 'StatusOnHour',
      },
      {
        title: getTranslatedValue('power_interruption'),
        fieldName: 'StatusPowerInterruption',
      },
    ],
  },
  {
    id: 'Meter.Info',
    label: getTranslatedValue('Meter.Info'),
    values: [
      {
        title: getTranslatedValue('StatusDigitalInput1'),
        fieldName: 'StatusDigitalInput1',
      },
      {
        title: getTranslatedValue('StatusDigitalInput2'),
        fieldName: 'StatusDigitalInput2',
      },
      {
        title: getTranslatedValue('StatusDigitalInput3'),
        fieldName: 'StatusDigitalInput3',
      },
      {
        title: getTranslatedValue('StatusDigitalInput4'),
        fieldName: 'StatusDigitalInput4',
      },
      {
        title: getTranslatedValue('StatusDigitalInput5'),
        fieldName: 'StatusDigitalInput5',
      },
      {
        title: getTranslatedValue('StatusDigitalInput6'),
        fieldName: 'StatusDigitalInput6',
      },
      {
        title: getTranslatedValue('StatusDigitalInput7'),
        fieldName: 'StatusDigitalInput7',
      },
    ],
  },
];

export const SAMPLE_TABLE_DATA = [
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
];
