import { getTranslatedValue } from '@/helpers/get-translated-value';
import { CheckboxGroup } from '@/types/pages/reports/reports';

export const monthlyDemandReportFields: CheckboxGroup[] = [
  {
    id: 'PhaseNo',
    label: getTranslatedValue('PhaseNo'),
    values: [
      { title: '1. Faz', fieldName: 'indActive1Imp' },
      { title: '2. Faz', fieldName: 'indActive1T1Imp' },
      { title: '3. Faz', fieldName: 'indActive1T2Imp' },
    ],
  },
];

export const SAMPLE_TABLE_DATA = [
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    startDate: '2025-07-01 10',
    endDate: '2025-07-01 10',
    consumptionValue: '2025-07-01 10',
    unit: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    startDate: '2025-07-01 10',
    endDate: '2025-07-01 10',
    consumptionValue: '2025-07-01 10',
    unit: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
];
