import { getTranslatedValue } from '@/helpers/get-translated-value';
import { CheckboxGroup } from '@/types/pages/reports/reports';

export const harmonicReportFields: CheckboxGroup[] = [
  {
    id: 'Faz No',
    label: getTranslatedValue('em_phase_nr'),
    values: [
      { title: '1.Faz', fieldName: 'PhaseL1' },
      { title: '2.Faz', fieldName: 'PhaseL2' },
      { title: '3.Faz', fieldName: 'PhaseL3' },
    ],
  },
  {
    id: 'Harmonik Tipi',
    label: getTranslatedValue('em_harmonic_type'),
    values: [
      { title: 'Gerilim', fieldName: 'HarmonicTypeVoltage' },
      { title: 'Akim', fieldName: 'HarmonicTypeCurrent' },
    ],
  },
  {
    id: 'Harmonik Sırası(1-17)',
    label: getTranslatedValue('em_harmonic_sequence'),
    values: [
      { title: 'Har.1', fieldName: 'Harmonic1' },
      { title: 'Har.3', fieldName: 'Harmonic3' },
      { title: 'Har.5', fieldName: 'Harmonic5' },
      { title: 'Har.7', fieldName: 'Harmonic7' },
      { title: 'Har.9', fieldName: 'Harmonic9' },
      { title: 'Har.11', fieldName: 'Harmonic11' },
      { title: 'Har.13', fieldName: 'Harmonic13' },
      { title: 'Har.15', fieldName: 'Harmonic15' },
      { title: 'Har.17', fieldName: 'Harmonic17' },
    ],
  },
  {
    id: 'Harmonik Sırası(19-35)',
    label: getTranslatedValue('em_harmonic_sequence'),
    values: [
      { title: 'Har.19', fieldName: 'Harmonic19' },
      { title: 'Har.21', fieldName: 'Harmonic21' },
      { title: 'Har.23', fieldName: 'Harmonic23' },
      { title: 'Har.25', fieldName: 'Harmonic25' },
      { title: 'Har.27', fieldName: 'Harmonic27' },
      { title: 'Har.29', fieldName: 'Harmonic29' },
      { title: 'Har.31', fieldName: 'Harmonic31' },
      { title: 'Har.33', fieldName: 'Harmonic33' },
      { title: 'Har.35', fieldName: 'Harmonic35' },
    ],
  },
  {
    id: 'Harmonik Sırası(37-51)',
    label: getTranslatedValue('em_harmonic_sequence'),
    values: [
      { title: 'Har.37', fieldName: 'Harmonic37' },
      { title: 'Har.39', fieldName: 'Harmonic39' },
      { title: 'Har.41', fieldName: 'Harmonic41' },
      { title: 'Har.43', fieldName: 'Harmonic43' },
      { title: 'Har.45', fieldName: 'Harmonic45' },
      { title: 'Har.47', fieldName: 'Harmonic47' },
      { title: 'Har.49', fieldName: 'Harmonic49' },
      { title: 'Har.51', fieldName: 'Harmonic51' },
    ],
  },
];

export const SAMPLE_TABLE_DATA = [
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
];
