import { getTranslatedValue } from '@/helpers/get-translated-value';
import { CheckboxGroup } from '@/types/pages/reports/reports';

export const minMaxReportFields: CheckboxGroup[] = [
  {
    id: 'Minimum Gerilim',
    label: getTranslatedValue('minimum')+ ' ' + getTranslatedValue('em_instant_voltage'),
    values: [
      { title: 'Ort.', fieldName: 'MinVoltAvg' },
      { title: '1.Faz', fieldName: 'MinVoltPhase1' },
      { title: '2.Faz', fieldName: 'MinVoltPhase2' },
      { title: '3.Faz', fieldName: 'MinVoltPhase3' },
    ],
  },
  {
    id: 'Maksimum Gerilim',
    label: getTranslatedValue('maximum') + ' ' + getTranslatedValue('em_instant_voltage'),
    values: [
      { title: 'Ort.', fieldName: 'MaxVoltAvg' },
      { title: '1.Faz', fieldName: 'MaxVoltPhase1' },
      { title: '2.Faz', fieldName: 'MaxVoltPhase2' },
      { title: '3.Faz', fieldName: 'MaxVoltPhase3' },
    ],
  },
  {
    id: 'Minimum Gerilim',
    label: getTranslatedValue('minimum') +' ' + getTranslatedValue('em_instant_voltage_line_line'),
    values: [
      { title: 'LL Ort.', fieldName: 'MinVoltLLAvg' },
      { title: 'LL 1-2', fieldName: 'MinVoltLL12' },
      { title: 'LL 2-3', fieldName: 'MinVoltLL23' },
      { title: 'LL 3-1', fieldName: 'MinVoltLL31' },
    ],
  },
  {
    id: 'Maksimum Gerilim',
    label: getTranslatedValue('maximum') +' ' +  getTranslatedValue('em_instant_voltage_line_line'),
    values: [
      { title: 'LL Ort.', fieldName: 'MaxVoltLLAvg' },
      { title: 'LL 1-2', fieldName: 'MaxVoltLL12' },
      { title: 'LL 2-3', fieldName: 'MaxVoltLL23' },
      { title: 'LL 3-1', fieldName: 'MaxVoltLL31' },
    ],
  },
  {
    id: 'Minimum Akım',
    label: getTranslatedValue('Current.Min'),
    values: [
      { title: 'Toplam', fieldName: 'MinCurTotal' },
      { title: '1.Faz', fieldName: 'MinCurPhase1' },
      { title: '2.Faz', fieldName: 'MinCurPhase2' },
      { title: '3.Faz', fieldName: 'MinCurPhase3' },
    ],
  },
  {
    id: 'Maksimum Akım',
    label: getTranslatedValue('Current.Max'),
    values: [
      { title: 'Toplam', fieldName: 'MaxCurTotal' },
      { title: '1.Faz', fieldName: 'MaxCurPhase1' },
      { title: '2.Faz', fieldName: 'MaxCurPhase2' },
      { title: '3.Faz', fieldName: 'MaxCurPhase3' },
    ],
  },
  {
    id: 'Minimum Aktif Güç',
    label: getTranslatedValue('ActivePower.Min'),
    values: [
      { title: 'Toplam', fieldName: 'MinActPowerTotal' },
      { title: '1.Faz', fieldName: 'MinActPowerPhase1' },
      { title: '2.Faz', fieldName: 'MinActPowerPhase2' },
      { title: '3.Faz', fieldName: 'MinActPowerPhase3' },
    ],
  },
  {
    id: 'Maksimum Aktif Güç',
    label: getTranslatedValue('ActivePower.Max'),
    values: [
      { title: 'Toplam', fieldName: 'MaxActPowerTotal' },
      { title: '1.Faz', fieldName: 'MaxActPowerPhase1' },
      { title: '2.Faz', fieldName: 'MaxActPowerPhase2' },
      { title: '3.Faz', fieldName: 'MaxActPowerPhase3' },
    ],
  },
  {
    id: 'Minimum Reaktif Güç',
    label: getTranslatedValue('ReactivePower.Min'),
    values: [
      { title: 'Toplam', fieldName: 'MinReactPowerTotal' },
      { title: '1.Faz', fieldName: 'MinReactPowerPhase1' },
      { title: '2.Faz', fieldName: 'MinReactPowerPhase2' },
      { title: '3.Faz', fieldName: 'MinReactPowerPhase3' },
    ],
  },
  {
    id: 'Maksimum Reaktif Güç',
    label: getTranslatedValue('ReactivePower.Max'),
    values: [
      { title: 'Toplam', fieldName: 'MaxReactPowerTotal' },
      { title: '1.Faz', fieldName: 'MaxReactPowerPhase1' },
      { title: '2.Faz', fieldName: 'MaxReactPowerPhase2' },
      { title: '3.Faz', fieldName: 'MaxReactPowerPhase3' },
    ],
  },
  {
    id: 'Minimum Görünür Güç',
    label: getTranslatedValue('ApparentPower.Min'),
    values: [
      { title: 'Toplam', fieldName: 'MinApperantPowerTotal' },
      { title: '1.Faz', fieldName: 'MinApperantPowerPhase1' },
      { title: '2.Faz', fieldName: 'MinApperantPowerPhase2' },
      { title: '3.Faz', fieldName: 'MinApperantPowerPhase3' },
    ],
  },
  {
    id: 'Maksimum Görünür Güç',
    label: getTranslatedValue('ApparentPower.Max'),
    values: [
      { title: 'Toplam', fieldName: 'MaxApperantPowerTotal' },
      { title: '1.Faz', fieldName: 'MaxApperantPowerPhase1' },
      { title: '2.Faz', fieldName: 'MaxApperantPowerPhase2' },
      { title: '3.Faz', fieldName: 'MaxApperantPowerPhase3' },
    ],
  },
  {
    id: 'Minimum Güç Faktörü',
    label: getTranslatedValue('PowerFactor.Min'),
    values: [
      { title: 'Ort.', fieldName: 'MinPowerFactorAvg' },
      { title: '1.Faz', fieldName: 'MinPowerFactorPhase1' },
      { title: '2.Faz', fieldName: 'MinPowerFactorPhase2' },
      { title: '3.Faz', fieldName: 'MinPowerFactorPhase3' },
    ],
  },
  {
    id: 'Maksimum Güç Faktörü',
    label: getTranslatedValue('PowerFactor.Max'),
    values: [
      { title: 'Ort.', fieldName: 'MaxPowerFactorAvg' },
      { title: '1.Faz', fieldName: 'MaxPowerFactorPhase1' },
      { title: '2.Faz', fieldName: 'MaxPowerFactorPhase2' },
      { title: '3.Faz', fieldName: 'MaxPowerFactorPhase3' },
    ],
  },
  {
    id: 'Cosø',
    label: getTranslatedValue('em_instant_cos'),
    values: [
      { title: 'Sistem', fieldName: 'MinCosAvg' },
      { title: '1.Faz', fieldName: 'MinCosPhase1' },
      { title: '2.Faz', fieldName: 'MinCosPhase2' },
      { title: '3.Faz', fieldName: 'MinCosPhase3' },
    ],
  },
  {
    id: 'Cosø',
    label: getTranslatedValue('em_instant_cos'),
    values: [
      { title: 'Sistem', fieldName: 'MaxCosAvg' },
      { title: '1.Faz', fieldName: 'MaxCosPhase1' },
      { title: '2.Faz', fieldName: 'MaxCosPhase2' },
      { title: '3.Faz', fieldName: 'MaxCosPhase3' },
    ],
  },
  {
    id: 'Minimum Frekans',
    label: getTranslatedValue('MinFrequency'),
    values: [
      { title: 'Toplam', fieldName: 'MinFrequency' },
      { title: '1.Faz', fieldName: 'MinFrequencyPhase1' },
      { title: '2.Faz', fieldName: 'MinFrequencyPhase2' },
      { title: '3.Faz', fieldName: 'MinFrequencyPhase3' },
    ],
  },
  {
    id: 'Maksimum Frekans',
    label: getTranslatedValue('MaxFrequency'),
    values: [
      { title: 'Toplam', fieldName: 'MaxFrequency' },
      { title: '1.Faz', fieldName: 'MaxFrequencyPhase1' },
      { title: '2.Faz', fieldName: 'MaxFrequencyPhase2' },
      { title: '3.Faz', fieldName: 'MaxFrequencyPhase3' },
    ],
  },
  {
    id: 'Minimum THD.Gerilim',
    label: getTranslatedValue('THD.Voltage.Min'),
    values: [
      { title: 'Toplam', fieldName: 'MinTHDVoltageTotal' },
      { title: '1.Faz', fieldName: 'MinTHDVoltagePhase1' },
      { title: '2.Faz', fieldName: 'MinTHDVoltagePhase2' },
      { title: '3.Faz', fieldName: 'MinTHDVoltagePhase3' },
    ],
  },
  {
    id: 'Maksimum THD.Gerilim',
    label: getTranslatedValue('THD.Voltage.Max'),
    values: [
      { title: 'Toplam', fieldName: 'MaxTHDVoltageTotal' },
      { title: '1.Faz', fieldName: 'MaxTHDVoltagePhase1' },
      { title: '2.Faz', fieldName: 'MaxTHDVoltagePhase2' },
      { title: '3.Faz', fieldName: 'MaxTHDVoltagePhase3' },
    ],
  },
  {
    id: 'Minimum THD.Akım',
    label: getTranslatedValue('THD.Current.Min'),
    values: [
      { title: 'Min Nötr Akım', fieldName: 'MinTHDCurrentTotal' },
      { title: '1.Faz', fieldName: 'MinTHDCurrentPhase1' },
      { title: '2.Faz', fieldName: 'MinTHDCurrentPhase2' },
      { title: '3.Faz', fieldName: 'MinTHDCurrentPhase3' },
    ],
  },
  {
    id: 'Maksimum THD.Akım',
    label: getTranslatedValue('THD.Current.Max'),
    values: [
      { title: 'Max Nötr Akım', fieldName: 'MaxTHDCurrentTotal' },
      { title: '1.Faz', fieldName: 'MaxTHDCurrentPhase1' },
      { title: '2.Faz', fieldName: 'MaxTHDCurrentPhase2' },
      { title: '3.Faz', fieldName: 'MaxTHDCurrentPhase3' },
    ],
  },
];

export const SAMPLE_TABLE_DATA = [
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
  {
    id: 482200,
    deviceId: 429,
    deviceDescription: 'Kys. Plot A Kalite Kaydedici',
    deviceModelName: 'Kayseri/RTU/E.K.K.',
    deviceOrganizationName: 'Plot A Kamber GES / Kayseri Yekdem GES / Kayseri',
    deviceModelCode: 'Kayseri/RTU/E.K.K.',
    deviceCategoryId: 12,
    deviceModelId: 1224,
    consDate: '2025-07-01 10',
    readDateTime: '2025-07-01 10',
    indActive1Imp: 100,
    indActive1T1Imp: 200,
    indActive1T2Imp: 300,
    indActive1T3Imp: 800,
    indActive2Imp: null,
    indReactive1Imp: null,
    indReactive1T1Imp: null,
    indReactive1T2Imp: null,
    indReactive1T3Imp: null,
    indReactive2Imp: null,
    indReactiveInd1Imp: 0,
    indReactiveInd1T1Imp: null,
    indReactiveInd1T2Imp: null,
    indReactiveInd1T3Imp: null,
    indReactiveInd2Imp: null,
    indReactiveCap1Imp: null,
    indReactiveCap1T1Imp: null,
    indReactiveCap1T2Imp: null,
    indReactiveCap1T3Imp: null,
    indReactiveCap2Imp: null,
    calculatedIndActive1Exp: 857,
    calculatedIndActive1T1Exp: null,
    calculatedIndActive1T2Exp: null,
    calculatedIndActive1T3Exp: null,
    indActive2Exp: null,
    indReactive1Exp: 61,
    indReactive1T1Exp: null,
    indReactive1T2Exp: null,
    indReactive1T3Exp: null,
    indReactive2Exp: null,
    indReactiveInd1Exp: null,
    indReactiveInd1T1Exp: null,
    indReactiveInd1T2Exp: null,
    indReactiveInd1T3Exp: null,
    indReactiveInd2Exp: null,
    indReactiveCap1Exp: null,
    indReactiveCap1T1Exp: null,
    indReactiveCap1T2Exp: null,
    indReactiveCap1T3Exp: null,
    indReactiveCap2Exp: null,
    indActivePowImp: null,
    indActivePowExp: null,
    deviceVoltTransValue: 1,
    deviceCurrTransValue: 1,
    capacitiveRate: 0,
    inductiveRate: 0,
  },
];
