import { getTranslatedValue } from '@/helpers/get-translated-value';
import * as yup from 'yup';

export const deviceModelInitialValues = {
  active: true,
  deviceModelCode: '',
  deviceModelTypeId: 0,
  deviceModelName: '',
  deviceModelIsOur: true,
  deviceModelProtocolId: -1,
  deviceModelDescription: '',
  deviceModelBaudRate: 0,
  deviceModelDataBit: 0,
  deviceModelParity: 0,
  deviceModelStopBit: 0,
  willTopic: '',
  writeFunction: 0,
  archivePeriodRegisterCount: 0,
  hourlyArchiveTotalCount: 0,
  hourlyArchiveStartAddress: 0,
  dailyArchiveTotalCount: 0,
  dailyArchiveStartAddress: 0,
  monthlyArchiveTotalCount: 0,
  monthlyArchiveStartAddress: 0,
  deviceModelId: 0,
  elecInstantValue: 0,
  elecInstantValueSave: 0,
  elecInstantValueLMED: null,
  elecHarmonic: 0,
  elecHarmonicSave: 0,
  elecHarmonicLMED: null,
  elecIndexValue: 0,
  elecIndexValueSave: 0,
  elecIndexValueLMED: null,
  elecDemandInstant: 0,
  elecDemandInstantSave: 0,
  elecDemandInstantLMED: null,
  elecDemandMonthly: 0,
  elecDemandMonthlySave: 0,
  elecDemandMonthlyLMED: null,
  elecAlarmLog: 0,
  elecAlarmLogSave: 0,
  elecAlarmLogLMED: null,
  elecMinMaxValue: 0,
  elecMinMaxValueSave: 0,
  elecMinMaxValueLMED: null,
  elecStep: 0,
  elecStepSave: 0,
  elecStepLMED: null,
  elecDigInputLog: 0,
  elecDigInputLogSave: 0,
  elecDigInputLogLMED: null,
  elecArchive: 0,
  elecArchiveSave: 0,
  elecArchiveLMED: null,
  elecStatusValue: 0,
  elecStatusValueSave: 0,
  elecStatusValueLMED: null,
  ioDeviceSensorValue: 0,
  ioDeviceSensorValueSave: 0,
  ioDeviceSensorValueLMED: null,
  ioDeviceCounterValue: 0,
  ioDeviceCounterValueSave: 0,
  ioDeviceCounterValueLMED: null,
  generatorValue: 0,
  generatorValueSave: 0,
  generatorValueLMED: null,
  compressorValue: 0,
  compressorValueSave: 0,
  compressorValueLMED: null,
  ngInstantMeasurementValue: 0,
  ngInstantMeasurementValueSave: 0,
  ngInstantMeasurementValueLMED: null,
  ngComponentValue: 0,
  ngComponentValueSave: 0,
  ngComponentValueLMED: null,
  ngArchive: 0,
  ngArchiveSave: 0,
  ngArchiveLMED: null,
  fmInstantValue: 0,
  fmInstantValueSave: 0,
  fmInstantValueLMED: null,
  ngChromatography: 0,
  ngChromatographySave: 0,
  ngChromatographyLMED: null,
  elecInverterInstantValue: 0,
  elecInverterInstantValueSave: 0,
  elecInverterInstantValueLMED: null,
};

const nullableNumberWithNullDefault = () =>
  yup
    .number()
    .nullable()
    .default(null)
    .transform((v) => (v === undefined ? null : v));

export const addDeviceModelResolver = yup.object({
  active: yup.boolean().required(),
  deviceModelCode: yup
    .string()
    .required(
      `${getTranslatedValue('DeviceModelCode')} ${getTranslatedValue(
        'Required',
        'AbpIdentity.texts',
      )}`,
    ),
  deviceModelTypeId: yup
    .number()
    .transform((value, originalValue) => (originalValue === '' ? 0 : value))
    .required(
      `${getTranslatedValue('DeviceModelTypeId')} ${getTranslatedValue(
        'Required',
        'AbpIdentity.texts',
      )}`,
    ),
  deviceModelName: yup
    .string()
    .required(
      `${getTranslatedValue('DeviceModelName')} ${getTranslatedValue(
        'Required',
        'AbpIdentity.texts',
      )}`,
    ),
  deviceModelIsOur: yup.boolean().required(),
  deviceModelProtocolId: yup
    .number()
    .transform((value, originalValue) => (originalValue === '' ? -1 : value))
    .required(
      `${getTranslatedValue('DeviceModelProtocolId')} ${getTranslatedValue(
        'Required',
        'AbpIdentity.texts',
      )}`,
    ),
  deviceModelDescription: yup.string().default(''),

  deviceModelBaudRate: yup.number().required(),
  deviceModelDataBit: yup.number().required(),
  deviceModelParity: yup.number().required(),
  deviceModelStopBit: yup.number().required(),
  willTopic: yup.string().default(''),
  writeFunction: yup.number().default(0),
  archivePeriodRegisterCount: yup.number().required(),
  hourlyArchiveTotalCount: yup.number().required(),
  hourlyArchiveStartAddress: yup.number().required(),
  dailyArchiveTotalCount: yup.number().required(),
  dailyArchiveStartAddress: yup.number().required(),
  monthlyArchiveTotalCount: yup.number().required(),
  monthlyArchiveStartAddress: yup.number().required(),
  deviceModelId: yup.number().required(),
  elecInstantValue: yup.number().required(),
  elecInstantValueSave: yup.number().required(),
  elecHarmonic: yup.number().required(),
  elecHarmonicSave: yup.number().required(),
  elecIndexValue: yup.number().required(),
  elecIndexValueSave: yup.number().required(),
  elecDemandInstant: yup.number().required(),
  elecDemandInstantSave: yup.number().required(),
  elecDemandMonthly: yup.number().required(),
  elecDemandMonthlySave: yup.number().required(),
  elecAlarmLog: yup.number().required(),
  elecAlarmLogSave: yup.number().required(),
  elecMinMaxValue: yup.number().required(),
  elecMinMaxValueSave: yup.number().required(),
  elecStep: yup.number().required(),
  elecStepSave: yup.number().required(),
  elecDigInputLog: yup.number().required(),
  elecDigInputLogSave: yup.number().required(),
  elecArchive: yup.number().required(),
  elecArchiveSave: yup.number().required(),
  elecStatusValue: yup.number().required(),
  elecStatusValueSave: yup.number().required(),
  ioDeviceSensorValue: yup.number().required(),
  ioDeviceSensorValueSave: yup.number().required(),
  ioDeviceCounterValue: yup.number().required(),
  ioDeviceCounterValueSave: yup.number().required(),
  generatorValue: yup.number().required(),
  generatorValueSave: yup.number().required(),
  compressorValue: yup.number().required(),
  compressorValueSave: yup.number().required(),
  ngInstantMeasurementValue: yup.number().required(),
  ngInstantMeasurementValueSave: yup.number().required(),
  ngComponentValue: yup.number().required(),
  ngComponentValueSave: yup.number().required(),
  ngArchive: yup.number().required(),
  ngArchiveSave: yup.number().required(),
  fmInstantValue: yup.number().required(),
  fmInstantValueSave: yup.number().required(),
  ngChromatography: yup.number().required(),
  ngChromatographySave: yup.number().required(),
  elecInverterInstantValue: yup.number().required(),
  elecInverterInstantValueSave: yup.number().required(),

  // nullable with default null and transform:
  elecInstantValueLMED: nullableNumberWithNullDefault(),
  elecHarmonicLMED: nullableNumberWithNullDefault(),
  elecIndexValueLMED: nullableNumberWithNullDefault(),
  elecDemandInstantLMED: nullableNumberWithNullDefault(),
  elecDemandMonthlyLMED: nullableNumberWithNullDefault(),
  elecAlarmLogLMED: nullableNumberWithNullDefault(),
  elecMinMaxValueLMED: nullableNumberWithNullDefault(),
  elecStepLMED: nullableNumberWithNullDefault(),
  elecDigInputLogLMED: nullableNumberWithNullDefault(),
  elecArchiveLMED: nullableNumberWithNullDefault(),
  elecStatusValueLMED: nullableNumberWithNullDefault(),
  ioDeviceSensorValueLMED: nullableNumberWithNullDefault(),
  ioDeviceCounterValueLMED: nullableNumberWithNullDefault(),
  generatorValueLMED: nullableNumberWithNullDefault(),
  compressorValueLMED: nullableNumberWithNullDefault(),
  ngInstantMeasurementValueLMED: nullableNumberWithNullDefault(),
  ngComponentValueLMED: nullableNumberWithNullDefault(),
  ngArchiveLMED: nullableNumberWithNullDefault(),
  fmInstantValueLMED: nullableNumberWithNullDefault(),
  ngChromatographyLMED: nullableNumberWithNullDefault(),
  elecInverterInstantValueLMED: nullableNumberWithNullDefault(),
});

export type deviceModelInitialValuesTypes = yup.InferType<
  typeof addDeviceModelResolver
>;
