import { formatDateToCustomISO } from '@/helpers/bys/get-today-date';
import { getTranslatedValue } from '@/helpers/get-translated-value';
import * as Yup from 'yup';

export const reportsAddProfileSchema = Yup.object().shape({
  profileId: Yup.number().optional(),
  profileName: Yup.string().when('$isProfileNameRequired', {
    is: true,
    then: (schema) =>
      schema
        .trim()
        .required(getTranslatedValue('Required', 'AbpIdentity.texts')),
    otherwise: (schema) => schema.notRequired().nullable(), // when false, make it optional
  }),
  reportType: Yup.string().optional(),
  filterProfileFields: Yup.array().of(
    Yup.object().shape({
      fieldName: Yup.string().optional(),
      fieldType: Yup.number().optional(),
      filterProfileId: Yup.number().optional(),
      fieldValue: Yup.mixed()
        // .test(
        //   "is-valid",
        //   "fieldValue must be a string or an array of objects with id and caption",
        //   (value) =>
        //     typeof value === "string" ||
        //     (Array.isArray(value) &&
        //       value.every(
        //         (item) =>
        //           typeof item === "object" &&
        //           item !== null &&
        //           "id" in item &&
        //           typeof item.id === "number" &&
        //           "caption" in item &&
        //           typeof item.caption === "string",
        //       )),
        // )
        .optional(),
    }),
  ),
});

export const reportsAddProfileInitialValues = {
  profileId: 0,
  profileName: '',
  reportType: 'periodic-elec-prod-cons',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseNo',
      fieldType: 2,
      fieldValue: '0',
      filterProfileId: 0,
    },
    {
      fieldName: 'PeriodWindowSelectable',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'RangeStartHour',
      fieldType: 2,
      fieldValue: '0',
      filterProfileId: 0,
    },
    {
      fieldName: 'RangeEndHour',
      fieldType: 2,
      fieldValue: '23',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'inductiveRate',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'capacitiveRate',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActivePowImp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActivePowExp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations',
      fieldType: 4,
      fieldValue: '', //IF ANY CONFLICTS HAPPENED GO BACK TO EMPTY ARRAY
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileMonthlyDemandInitialValues = {
  profileName: '',
  reportType: 'device-elec-demand-monthlies',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemCurrent',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemCurrentDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowImp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowImpDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowExp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowExpDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemReactivePow',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemReactivePowDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations',
      fieldType: 4,
      fieldValue: '',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects',
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileHarmonicInitialValues = {
  profileName: '',
  reportType: 'device-elec-harmonics',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'HarmonicTypeVoltage',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'HarmonicTypeCurrent',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic5',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic7',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic9',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic11',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic13',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic15',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic17',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic19',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic21',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic23',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic25',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic27',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic29',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic31',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic33',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic35',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic37',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic39',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic41',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic43',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic45',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic47',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic49',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'Harmonic51',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations',
      fieldType: 4,
      fieldValue: '',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects',
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileMinimumMaximumInitialValues = {
  profileName: '',
  reportType: 'device-elec-min-max-values',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltLLAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltLL12',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltLL23',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinVoltLL31',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltLLAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltLL12',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltLL23',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxVoltLL31',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCurTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCurPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCurPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCurPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCurTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCurPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCurPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCurPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinActPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinActPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinActPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinActPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxActPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxActPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxActPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxActPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinReactPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinReactPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinReactPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinReactPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxReactPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxReactPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxReactPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxReactPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinApperantPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinApperantPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinApperantPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinApperantPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxApperantPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxApperantPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxApperantPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxApperantPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinPowerFactorAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinPowerFactorPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinPowerFactorPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinPowerFactorPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxPowerFactorAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxPowerFactorPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxPowerFactorPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxPowerFactorPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCosAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCosPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCosPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinCosPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCosAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCosPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCosPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxCosPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinFrequency',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinFrequencyPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinFrequencyPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinFrequencyPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxFrequency',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxFrequencyPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxFrequencyPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxFrequencyPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDVoltageTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDVoltagePhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDVoltagePhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDVoltagePhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDVoltageTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDVoltagePhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDVoltagePhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDVoltagePhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDCurrentTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDCurrentPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDCurrentPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MinTHDCurrentPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDCurrentTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDCurrentPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDCurrentPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'MaxTHDCurrentPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileArchiveInitialValues = {
  profileName: '',
  reportType: 'io-device-archives',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase1Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase1Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase2Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase2Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase2Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase3Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase3Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltPNPhase3Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase1Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase1Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase2Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase2Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase2Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase3Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase3Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CurrentPhase3Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase1Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase1Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase2Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase2Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase2Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase3Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase3Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerPhase3Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase1Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase1Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase2Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase2Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase2Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase3Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase3Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReactivePowerPhase3Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase1Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase1Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase2Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase2Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase2Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase3Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase3Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ApparentPowerPhase3Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL12Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL12Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL12Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL23Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL23Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL23Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL31Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL31Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'VoltLL31Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CosPhiPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CosPhiPhase2Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'CosPhiPhase3Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PowerFactorPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PowerFactorPhase2Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PowerFactorPhase3Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'FreqPhase1Avg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'FreqPhase1Min',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'FreqPhase1Max',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyActiveImport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyActiveExport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyReactiveInductiveTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyReactiveCapacitiveTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyReactiveInductiveImport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyReactiveCapacitiveImport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyReactiveInductiveExport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'EnergyReactiveCapacitiveExport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerDemandImport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'ActivePowerDemandExport',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileIndexValuesInitialValues = {
  profileName: '',
  reportType: 'index-value',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseNo',
      fieldType: 2,
      fieldValue: '0',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'calculatedIndActive2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T4Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileInverterInstantValuesInitialValues = {
  profileName: '',
  reportType: 'inverter-instant-value',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACActPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invDCActPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACReactPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltLLAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltLL12',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltLL23',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACVoltLL31',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvACApperantPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvACPowerFactorAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvACCosAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvACFrequency',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACCurTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACCurPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACCurPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invACCurPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invCurrentDayProduction',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invWorkingTotalHour',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvDCVoltPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvDCVoltPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvDCVoltPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'InvDCVoltPhase4',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invStatus',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invManStatus',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invDCCurrPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invDCCurrPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invDCCurrPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invDCCurrPhase4',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invInnerTemperature',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invHeatSinkTemperature',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invTransformerTemperature',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invOtherTemperature',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invStringCurrPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invStringCurrPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invStringCurrPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'invStringCurrPhase4',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileSensorValueReportInitialValues = {
  profileName: '',
  reportType: 'sensor-value',
  filterProfileFields: [
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'Label',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    // {
    //   fieldName: "invACVoltAvg",
    //   fieldType: 1,
    //   fieldValue: "False",
    //   filterProfileId: 0,
    // },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileSystemAlarmReportInitialValues = {
  profileName: '',
  reportType: 'system-alarm',
  filterProfileFields: [
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'AlarmStatus',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'AlarmApproval',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'Label',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'AlarmLevel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileWeatherReportInitialValues = {
  profileName: '',
  reportType: 'weather',
  filterProfileFields: [
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'City',
      fieldType: 2,
      fieldValue: '0',
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileElecProdConsInitialValues = {
  profileName: '',
  reportType: 'elec-prod-cons',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseNo',
      fieldType: 2,
      fieldValue: '0',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1Imp',
      fieldType: 1,
      fieldValue: 'True',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1Exp',
      fieldType: 1,
      fieldValue: 'True',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indActive2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T1Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T3Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive2Imp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactive2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveInd2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T1Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap1T3Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'indReactiveCap2Exp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'inductiveRate',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'capacitiveRate',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileInstantValueInitialValues = {
  profileName: '',
  reportType: 'instant-value',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'ReportPeriod',
      fieldType: 2,
      fieldValue: '1',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltLLAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltLL12',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltLL23',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insVoltLL31',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCurTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCurPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCurPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCurPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCurNeutral',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insApperantPowerTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insApperantPowerPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insApperantPowerPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insApperantPowerPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insPowerFactorAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insPowerFactorPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insPowerFactorPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insPowerFactorPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCosAvg',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCosPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCosPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insCosPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insFrequency',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insFrequencyPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insFrequencyPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insFrequencyPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerExpTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerExpPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerExpPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insActPowerExpPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerExpTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerExpPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerExpPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insReactPowerExpPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDVoltageTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDVoltagePhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDVoltagePhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDVoltagePhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDCurrentTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDCurrentPhase1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDCurrentPhase2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'insTHDCurrentPhase3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileEnergyIndexInitialValues = {
  profileName: '',
  reportType: 'device-energy-index-values',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModelName',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileDemandInitialValues = {
  profileId: 0,
  profileName: '',
  reportType: 'device-elec-demand-instants',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseTotal',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'PhaseL3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemCurrent',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemCurrentDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowImp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowImpDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowExp',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemActivePowExpDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemReactivePow',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'DemReactivePowDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations',
      fieldType: 4,
      fieldValue: '',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects',
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};

export const reportsAddProfileDeviceStatusInitialValues = {
  profileName: '',
  reportType: 'device-elec-status-values',
  filterProfileFields: [
    {
      fieldName: 'StartDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(-1),
      filterProfileId: 0,
    },
    {
      fieldName: 'EndDateTime',
      fieldType: 3,
      fieldValue: formatDateToCustomISO(0),
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceCategory',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'DeviceModel',
      fieldType: 2,
      fieldValue: '-1',
      filterProfileId: 0,
    },
    {
      fieldName: 'InsDeviceDateTime',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusBatteryVoltage',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusTemperature',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusGenaratorFlag',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusAlarmFlag1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusAlarmFlag2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInputFlag',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalOutputFlag',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusRunHour',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusOnHour',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusPowerInterruption',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInput1',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInput2',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInput3',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInput4',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInput5',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInput6',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'StatusDigitalInput7',
      fieldType: 1,
      fieldValue: 'False',
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizations', // 1;2;3
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
    {
      fieldName: 'SelectedOrganizationsObjects', // [{id:1,caption:"Organization1"},{id:2,caption:"Organization2"},{id:3,caption:"Organization3"}]
      fieldType: 4,
      fieldValue: [],
      filterProfileId: 0,
    },
  ],
};
