export const englishLocalization = {
  WebNet: {
    texts: {
      'WidgetHeader:TotalPower': 'Total Power',
      IndCurrentDayActive1ExpCons: "Today's Production",
      IndCurrentMonthActive1ExpCons: "This Month's Production",
      IndCurrentYearActive1ExpCons: "This Year's Production",
      production_revenue: 'Production Revenue',
      today: 'Today',
      Forecast: 'Forecast',

      re_plant_summary: 'Plant Summary',
      re_summary: 'Summary',
      firm_communication_info: 'Communication Info',
      organization_alarm: 'Alarms',
      authExtraReporting: 'Extra Reports',
      ColumnsList: 'Columns List',
      AlarmDetails: 'Alarm Details',

      re_plant_production_comparison: 'Plant Production Comparison',
      em_org_plant_detail: 'Plant Details',
      re_plant_forecast: 'Production Forecast',
      TrendAnalysis: 'Trend Analysis',

      em_org_plant_name: 'Plant Name',
      em_energy_type: 'Energy Type',
      em_org_plant_weather_info: 'Weather',
      em_inv_dc_rated_power: 'DC Rated Power',
      em_inv_ac_limited_power: 'AC Limited Power',
      production_active_power: 'Active Power',
      radiation: 'Radiation',
      em_re_production: 'Production',
      em_re_spr: 'Specific Yield',
      em_re_specific_production: 'Specific Production',
      em_re_eao: 'EAO',
      em_re_inverter_status: 'Inverter Status',
      last_success_communication_time: 'Last Communication',

      'Enum:PlantEnergyType.SunLand': 'Sunland',
      'Enum:PlantEnergyType.Wind': 'Wind',
      'Enum:PlantEnergyType.Hydro': 'Hydro',
      'Enum:PlantEnergyType.SunRoof': 'SunRoof',
      DeviceDescription: 'Device Description',
      DeviceDCRatedPower: 'DC Rated Power',
      DeviceACRatedPower: 'AC Rated Power',
      DeviceACLimitedPower: 'AC Limited Power',
      ActivePowerWUnit: 'Active Power (W)',
      ComparisonWUnit: 'Comparison (W)',
      Production: 'Production',
      ActiveAlarmCount: 'Active Alarm Count',
      DeviceLastSuccessComm: 'Last Successful Communication',
    },
  },
  AbpUi: {
    texts: {
      Clear: 'Clear',
    },
  },
};
