export const mockOrgIds = [1];

export const mockOrgData = {
  id: 1,
  organizationName: 'Arma Solar Plant',
  organizationParentNames: 'Arma Energy Group / Solar Division',
  organizationPlantMimicDiagramId: 250,
  deviceMimicDiagramId: null,
  organizationCode: 'ARM-SOL-101',
  createdDate: '2026-05-22T08:00:00Z',
  orgType: 0,
  orgTreeType: 1,
  deviceType: 0,
  type: 0,
  active: true,
  hasActiveAlarm: 2,
  organizationType: 0,
  organizationTreeNodeType: 1,
  deviceModelType: 0,
  deviceModelId: null,
  locationId: 34,
};

export const mockCurrentOrgData = {
  id: 601,
  organizationName: 'Inverter 01',
  organizationParentNames: 'Arma Energy Group / Solar Division / PV Plant A',
  locationId: 12,
  deviceMimicDiagramId: 555,
  organizationPlantMimicDiagramId: 260,
  organizationType: 6,
  deviceSerial: 'INV-0001',
};
export const mockPlantSummaryData = [
  {
    organizationName: 'Solar Horizon Park',
    commActiveAlarmCount: 3,
    organizationPlantEnergyType: 1,
    weatherImage: 'sunny.png',
    deviceDCRatedPower: 5000.5,
    deviceACLimitedPower: 4500,
    invACActPowerTotal: 4200.25,
    compensatedRadiation: 850.12,
    production: 12500.75,
    em_re_spr: 0.92,
    specificProduction: 1.45,
    eao: 98.5,
    inverterCount: 10,
    inverterWorkCount: 9,
    deviceLastSuccessComm: '2026-05-22T10:00:00Z',
  },
  {
    organizationName: 'Wind Valley Farm',
    commActiveAlarmCount: 0,
    organizationPlantEnergyType: 2,
    weatherImage: 'cloudy.png',
    deviceDCRatedPower: 12000,
    deviceACLimitedPower: 11000,
    invACActPowerTotal: 9800,
    compensatedRadiation: 0,
    production: 35000,
    em_re_spr: 0.88,
    specificProduction: 2.1,
    eao: 99.2,
    inverterCount: 20,
    inverterWorkCount: 20,
    deviceLastSuccessComm: '2026-05-22T09:45:00Z',
  },
  {
    organizationName: 'Hydro Peak Station',
    commActiveAlarmCount: 0,
    organizationPlantEnergyType: 3,
    weatherImage: null,
    deviceDCRatedPower: 8000,
    deviceACLimitedPower: 7500,
    invACActPowerTotal: 7200,
    compensatedRadiation: 0,
    production: 20000,
    em_re_spr: 0.95,
    specificProduction: 1.8,
    eao: 99.9,
    inverterCount: 5,
    inverterWorkCount: 4,
    deviceLastSuccessComm: null,
  },
];
