export const dummyTurkeyMapData = {
  districts: [
    {
      district: 'Adana',
      totalNotifications: 1200,
      scadaNotifications: 400,
      ososNotifications: 500,
      crmNotifications: 300,
    },
    {
      district: 'Adıyaman',
      totalNotifications: 800,
      scadaNotifications: 200,
      ososNotifications: 300,
      crmNotifications: 300,
    },
    {
      district: 'Afyonkarahisar',
      totalNotifications: 1500,
      scadaNotifications: 500,
      ososNotifications: 600,
      crmNotifications: 400,
    },
    {
      district: 'Ağrı',
      totalNotifications: 700,
      scadaNotifications: 200,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Amasya',
      totalNotifications: 900,
      scadaNotifications: 300,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Ankara',
      totalNotifications: 4000,
      scadaNotifications: 1500,
      ososNotifications: 1500,
      crmNotifications: 1000,
    },
    {
      district: 'Antalya',
      totalNotifications: 2500,
      scadaNotifications: 1000,
      ososNotifications: 800,
      crmNotifications: 700,
    },
    {
      district: 'Artvin',
      totalNotifications: 500,
      scadaNotifications: 200,
      ososNotifications: 150,
      crmNotifications: 150,
    },
    {
      district: 'Aydın',
      totalNotifications: 1800,
      scadaNotifications: 600,
      ososNotifications: 700,
      crmNotifications: 500,
    },
    {
      district: 'Balıkesir',
      totalNotifications: 1600,
      scadaNotifications: 500,
      ososNotifications: 600,
      crmNotifications: 500,
    },
    {
      district: 'Bilecik',
      totalNotifications: 400,
      scadaNotifications: 100,
      ososNotifications: 150,
      crmNotifications: 150,
    },
    {
      district: 'Bingöl',
      totalNotifications: 300,
      scadaNotifications: 100,
      ososNotifications: 100,
      crmNotifications: 100,
    },
    {
      district: 'Bitlis',
      totalNotifications: 600,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 200,
    },
    {
      district: 'Bolu',
      totalNotifications: 800,
      scadaNotifications: 300,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Burdur',
      totalNotifications: 700,
      scadaNotifications: 200,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Bursa',
      totalNotifications: 3500,
      scadaNotifications: 1200,
      ososNotifications: 1300,
      crmNotifications: 1000,
    },
    {
      district: 'Çanakkale',
      totalNotifications: 900,
      scadaNotifications: 300,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Çankırı',
      totalNotifications: 500,
      scadaNotifications: 150,
      ososNotifications: 200,
      crmNotifications: 150,
    },
    {
      district: 'Çorum',
      totalNotifications: 1000,
      scadaNotifications: 400,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Denizli',
      totalNotifications: 2000,
      scadaNotifications: 700,
      ososNotifications: 800,
      crmNotifications: 500,
    },
    {
      district: 'Diyarbakır',
      totalNotifications: 2500,
      scadaNotifications: 1000,
      ososNotifications: 900,
      crmNotifications: 600,
    },
    {
      district: 'Edirne',
      totalNotifications: 800,
      scadaNotifications: 300,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Elazığ',
      totalNotifications: 1200,
      scadaNotifications: 400,
      ososNotifications: 500,
      crmNotifications: 300,
    },
    {
      district: 'Erzincan',
      totalNotifications: 600,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 200,
    },
    {
      district: 'Erzurum',
      totalNotifications: 1000,
      scadaNotifications: 400,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Eskişehir',
      totalNotifications: 1500,
      scadaNotifications: 500,
      ososNotifications: 600,
      crmNotifications: 400,
    },
    {
      district: 'Gaziantep',
      totalNotifications: 3000,
      scadaNotifications: 1200,
      ososNotifications: 1000,
      crmNotifications: 800,
    },
    {
      district: 'Giresun',
      totalNotifications: 900,
      scadaNotifications: 300,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Gümüşhane',
      totalNotifications: 400,
      scadaNotifications: 100,
      ososNotifications: 150,
      crmNotifications: 150,
    },
    {
      district: 'Hakkari',
      totalNotifications: 300,
      scadaNotifications: 100,
      ososNotifications: 100,
      crmNotifications: 100,
    },
    {
      district: 'Hatay',
      totalNotifications: 2000,
      scadaNotifications: 700,
      ososNotifications: 800,
      crmNotifications: 500,
    },
    {
      district: 'Isparta',
      totalNotifications: 800,
      scadaNotifications: 300,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Mersin',
      totalNotifications: 2500,
      scadaNotifications: 1000,
      ososNotifications: 900,
      crmNotifications: 600,
    },
    {
      district: 'İstanbul',
      totalNotifications: 7000,
      scadaNotifications: 2500,
      ososNotifications: 2500,
      crmNotifications: 2000,
    },
    {
      district: 'İzmir',
      totalNotifications: 5000,
      scadaNotifications: 1800,
      ososNotifications: 1700,
      crmNotifications: 1500,
    },
    {
      district: 'Kars',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
    {
      district: 'Kastamonu',
      totalNotifications: 700,
      scadaNotifications: 200,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Kayseri',
      totalNotifications: 2000,
      scadaNotifications: 700,
      ososNotifications: 800,
      crmNotifications: 500,
    },
    {
      district: 'Kırklareli',
      totalNotifications: 500,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 100,
    },
    {
      district: 'Kırşehir',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
    {
      district: 'Kocaeli',
      totalNotifications: 2200,
      scadaNotifications: 800,
      ososNotifications: 700,
      crmNotifications: 700,
    },
    {
      district: 'Konya',
      totalNotifications: 2800,
      scadaNotifications: 1000,
      ososNotifications: 900,
      crmNotifications: 900,
    },
    {
      district: 'Kütahya',
      totalNotifications: 900,
      scadaNotifications: 300,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Malatya',
      totalNotifications: 1500,
      scadaNotifications: 500,
      ososNotifications: 600,
      crmNotifications: 400,
    },
    {
      district: 'Manisa',
      totalNotifications: 2000,
      scadaNotifications: 700,
      ososNotifications: 800,
      crmNotifications: 500,
    },
    {
      district: 'Kahramanmaraş',
      totalNotifications: 1800,
      scadaNotifications: 600,
      ososNotifications: 700,
      crmNotifications: 500,
    },
    {
      district: 'Mardin',
      totalNotifications: 800,
      scadaNotifications: 300,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Muğla',
      totalNotifications: 1500,
      scadaNotifications: 500,
      ososNotifications: 600,
      crmNotifications: 400,
    },
    {
      district: 'Muş',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
    {
      district: 'Nevşehir',
      totalNotifications: 600,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 200,
    },
    {
      district: 'Niğde',
      totalNotifications: 700,
      scadaNotifications: 200,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Ordu',
      totalNotifications: 1200,
      scadaNotifications: 400,
      ososNotifications: 500,
      crmNotifications: 300,
    },
    {
      district: 'Rize',
      totalNotifications: 900,
      scadaNotifications: 300,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Sakarya',
      totalNotifications: 1600,
      scadaNotifications: 500,
      ososNotifications: 600,
      crmNotifications: 500,
    },
    {
      district: 'Samsun',
      totalNotifications: 1500,
      scadaNotifications: 500,
      ososNotifications: 500,
      crmNotifications: 500,
    },
    {
      district: 'Siirt',
      totalNotifications: 300,
      scadaNotifications: 100,
      ososNotifications: 100,
      crmNotifications: 100,
    },
    {
      district: 'Sinop',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
    {
      district: 'Sivas',
      totalNotifications: 1000,
      scadaNotifications: 400,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Tekirdağ',
      totalNotifications: 900,
      scadaNotifications: 300,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Tokat',
      totalNotifications: 800,
      scadaNotifications: 300,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Trabzon',
      totalNotifications: 1300,
      scadaNotifications: 400,
      ososNotifications: 500,
      crmNotifications: 400,
    },
    {
      district: 'Tunceli',
      totalNotifications: 300,
      scadaNotifications: 100,
      ososNotifications: 100,
      crmNotifications: 100,
    },
    {
      district: 'Şanlıurfa',
      totalNotifications: 2200,
      scadaNotifications: 800,
      ososNotifications: 700,
      crmNotifications: 700,
    },
    {
      district: 'Uşak',
      totalNotifications: 600,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 200,
    },
    {
      district: 'Van',
      totalNotifications: 900,
      scadaNotifications: 300,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Yozgat',
      totalNotifications: 700,
      scadaNotifications: 200,
      ososNotifications: 300,
      crmNotifications: 200,
    },
    {
      district: 'Zonguldak',
      totalNotifications: 1000,
      scadaNotifications: 400,
      ososNotifications: 400,
      crmNotifications: 200,
    },
    {
      district: 'Aksaray',
      totalNotifications: 500,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 100,
    },
    {
      district: 'Bayburt',
      totalNotifications: 200,
      scadaNotifications: 100,
      ososNotifications: 50,
      crmNotifications: 50,
    },
    {
      district: 'Karaman',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
    {
      district: 'Kırıkkale',
      totalNotifications: 600,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 200,
    },
    {
      district: 'Batman',
      totalNotifications: 500,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 100,
    },
    {
      district: 'Şırnak',
      totalNotifications: 300,
      scadaNotifications: 100,
      ososNotifications: 100,
      crmNotifications: 100,
    },
    {
      district: 'Bartın',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
    {
      district: 'Ardahan',
      totalNotifications: 200,
      scadaNotifications: 100,
      ososNotifications: 50,
      crmNotifications: 50,
    },
    {
      district: 'Iğdır',
      totalNotifications: 300,
      scadaNotifications: 100,
      ososNotifications: 100,
      crmNotifications: 100,
    },
    {
      district: 'Yalova',
      totalNotifications: 500,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 100,
    },
    {
      district: 'Karabük',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
    {
      district: 'Kilis',
      totalNotifications: 300,
      scadaNotifications: 100,
      ososNotifications: 100,
      crmNotifications: 100,
    },
    {
      district: 'Osmaniye',
      totalNotifications: 500,
      scadaNotifications: 200,
      ososNotifications: 200,
      crmNotifications: 100,
    },
    {
      district: 'Düzce',
      totalNotifications: 400,
      scadaNotifications: 150,
      ososNotifications: 150,
      crmNotifications: 100,
    },
  ],
};
